# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PpDc1riBa0CLGqRcIoXZN28Td2t5fcV3
"""

import pandas

df = pandas.read_excel('excel.xls')
df = df.drop(index=[*[_ for _ in range(10)], *[_ for _ in range(len(df)-11, len(df))]])

cols = list(df.columns)
new_cols = ['Mes', 'Personas']

df = df.rename(columns={k:v for k,v in zip(cols, new_cols)})
df.Mes = df.Mes.str.replace(r'(\w+)( \w+)?', r'\1')
df = df[::-1]

index = pandas.MultiIndex.from_frame(df.Mes.str.split('M', expand=True).astype('int64'), names=['Año', 'Mes'])

data = df['Personas'].values.tolist()

df2 = pandas.DataFrame(data, index=index, columns=('Personas',))

df2.plot(figsize=(25, 5))
df2.mean(level=0).plot(xlim=(1997, 2019), figsize=(25, 5))
df2.min(level=0).plot(xlim=(1997, 2019), figsize=(25, 5))
df2.max(level=0).plot(xlim=(1997, 2019), figsize=(25, 5))

df2.unstack(level=0).plot(legend=True, figsize=(25, 10))

